# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0cfd7e3e0a4d666bdc639250dce636c3ffe6dfe9e8c97e3bb2b9a9cc8b640149382601f9e856e9ba94d9a25c9542560754a95e9f29951d177c3a914931875d1

test:
  secret_key_base: f421a0b809c40c2865993fbac19f33b9bea489354a8a1139960232baff794973ff3f5b487b817c3d040d64537e888452fe46c93a652de69c47090bbe323ad586

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
